version: '3.8'
services:
  postgres:
    image: postgres
    container_name: load_forecasting_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: something
      POSTGRES_DB: load_forecasting
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Persist PostgreSQL data
    restart: always
